version: '3.9'
services:
  postgres:
    image: postgres:15.1
    networks:
      - eis_service
    extra_hosts:
      - "host.docker.internal:${DOCKER_HOST_GATEWAY:-host-gateway}"
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=eisservice
      - POSTGRES_HOST_AUTH_METHOD=trust