### Publish
POST http://127.0.0.1:9100/publish
Content-Type: application/json

{}


### Get received
GET http://127.0.0.1:9100/received
Content-Type: application/json

{}

### Poll
POST http://127.0.0.1:9100/brokerless-events/outbox
Content-Type: application/json

{
  "eventTypes": ["brokerless.sampleapp.model.SampleEvent1", "brokerless.sampleapp.model.SampleEvent2"]
}
