spring:
  config:
    import: classpath:persistence.yaml
  cloud:
    kubernetes:
      enabled: false
server:
  port: 9100
logging:
  level:
    brokerless: trace
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
brokerless:
  consumer:
    producers: []
