spring:
  datasource:
    url: jdbc:h2:mem:brokerless
  h2:
    console:
      enabled: true
server:
  port: 9100
logging:
  level:
    brokerless: trace
management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true
brokerless:
  consumer:
    producers:
      - name: sample-application
        base-url: http://127.0.0.1:9100
