spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://127.0.0.1:5432/brokerless?autoreconnect=true"
    username: "postgres"
    password: ""
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migrations
    schemas: public
logging:
  level:
    org.flywaydb.core: DEBUG
